# Generated by Django 3.2.9 on 2021-11-15 15:04

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20211114_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orginal_cart',
            new_name='original_cart',
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
