# Generated by Django 3.2.9 on 2021-11-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='platorm',
            new_name='platform',
        ),
    ]
