# Generated by Django 3.2.9 on 2021-11-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_rename_platorm_orderlineitem_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_cost',
            new_name='discount_cost',
        ),
    ]
