# Generated by Django 3.2.9 on 2021-11-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='platorms',
            field=models.ManyToManyField(blank=True, null=True, to='products.Platorm'),
        ),
    ]
