# Generated by Django 3.2.9 on 2021-11-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_platorms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='platorms',
            field=models.ManyToManyField(to='products.Platorm'),
        ),
    ]
