# Generated by Django 3.2.9 on 2021-11-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_rename_platorm_orderlineitem_platform'),
        ('products', '0010_alter_product_platorms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platorm',
            new_name='Platform',
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name_plural': 'Platforms'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='platorms',
        ),
        migrations.AddField(
            model_name='product',
            name='platforms',
            field=models.ManyToManyField(to='products.Platform'),
        ),
    ]
