# Generated by Django 3.2.9 on 2021-11-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20211120_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
